-- Crear / migrar ContextoItem para Contexto Interno y Externo (características por categoría)
-- Uso: psql "postgresql://user:pass@host:5432/riesgos_db" -f create_contexto_item.sql

BEGIN;

-- 1) Crear tabla ContextoItem si no existe
CREATE TABLE IF NOT EXISTS "ContextoItem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "procesoId" INTEGER NOT NULL REFERENCES "Proceso"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "tipo" VARCHAR(255) NOT NULL,      -- ej. INTERNO_FINANCIEROS, EXTERNO_ECONOMICO
  "signo" VARCHAR(20) NOT NULL,      -- POSITIVO | NEGATIVO
  "descripcion" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "ContextoItem_procesoId_idx" ON "ContextoItem"("procesoId");

-- 2) Migrar información existente de la tabla Contexto (INTERNO_* y EXTERNO_*)
--    - Los tipos *_* se consideran POSITIVO
--    - Los tipos *_*_NEG se consideran NEGATIVO y se guardan en ContextoItem
--    - Se evita insertar duplicados si ya existen ContextoItem equivalentes

INSERT INTO "ContextoItem" ("procesoId", "tipo", "signo", "descripcion", "createdAt", "updatedAt")
SELECT
  c."procesoId",
  CASE
    WHEN c."tipo" LIKE 'INTERNO_%_NEG' OR c."tipo" LIKE 'EXTERNO_%_NEG' THEN regexp_replace(c."tipo", '_NEG$', '')
    ELSE c."tipo"
  END AS "tipo",
  CASE
    WHEN c."tipo" LIKE 'INTERNO_%_NEG' OR c."tipo" LIKE 'EXTERNO_%_NEG' THEN 'NEGATIVO'
    ELSE 'POSITIVO'
  END AS "signo",
  c."descripcion",
  COALESCE(c."createdAt", NOW()) AS "createdAt",
  COALESCE(c."updatedAt", NOW()) AS "updatedAt"
FROM "Contexto" c
WHERE (c."tipo" LIKE 'INTERNO_%' OR c."tipo" LIKE 'EXTERNO_%')
  AND c."descripcion" IS NOT NULL
  AND btrim(c."descripcion") <> ''
  AND NOT EXISTS (
    SELECT 1
    FROM "ContextoItem" ci
    WHERE ci."procesoId" = c."procesoId"
      AND ci."tipo" = CASE
                        WHEN c."tipo" LIKE 'INTERNO_%_NEG' OR c."tipo" LIKE 'EXTERNO_%_NEG' THEN regexp_replace(c."tipo", '_NEG$', '')
                        ELSE c."tipo"
                      END
      AND ci."signo" = CASE
                         WHEN c."tipo" LIKE 'INTERNO_%_NEG' OR c."tipo" LIKE 'EXTERNO_%_NEG' THEN 'NEGATIVO'
                         ELSE 'POSITIVO'
                       END
      AND ci."descripcion" = c."descripcion"
  );

-- 3) Añadir columnas para "Enviar a DOFA" y dimensión (si no existen)
ALTER TABLE "ContextoItem" ADD COLUMN IF NOT EXISTS "enviarADofa" BOOLEAN DEFAULT false;
ALTER TABLE "ContextoItem" ADD COLUMN IF NOT EXISTS "dofaDimension" VARCHAR(50);

-- 4) (Opcional) Limpiar Contexto antiguo (interno + externo).
--    Si ya no quieres usar la tabla Contexto para INTERNO_* / EXTERNO_*, descomenta el DELETE.

-- DELETE FROM "Contexto"
-- WHERE "tipo" LIKE 'INTERNO_%' OR "tipo" LIKE 'EXTERNO_%';

COMMIT;
